-- expression: (x and y and (not z)) or ((not y) and x)
-- The parentheses are not nessesary because these parentheses
-- group operands in the same precedence as without them.
--
-- I would recommend their use because in that expression 
-- because they can increase readibily
